Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30 # Raise the limit

Metrics/BlockLength:
  Max: 45 # Raise the limit
  Exclude:
    - "spec/**/*_spec.rb"

Layout/LineLength:
  Exclude:
    - "spec/**/*_spec.rb"

Style/NumericLiterals:
  Exclude:
    - "spec/**/*_spec.rb"

Metrics/AbcSize:
  Max: 25 # or whatever feels acceptable

Style/FormatString:
  Enabled: false

AllCops:
  SuggestExtensions: false
